name: Python Security Scanning

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  security-scan:
    name: Python Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    
    strategy:
      matrix:
        scanner: [trivy, snyk, bandit, safety, pip-audit]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run Trivy Scanner
        if: matrix.scanner == 'trivy'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Run Snyk Scanner
        if: matrix.scanner == 'snyk'
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium --json-file-output=snyk-results.json
        continue-on-error: true

      - name: Run Bandit Security Linter
        if: matrix.scanner == 'bandit'
        run: |
          pip install bandit[toml]
          bandit -r . -f json -o bandit-results.json || true
          bandit -r . -f sarif -o bandit-results.sarif || true

      - name: Run Safety Check
        if: matrix.scanner == 'safety'
        run: |
          pip install safety
          safety check --json --output safety-results.json || true

      - name: Run pip-audit
        if: matrix.scanner == 'pip-audit'
        run: |
          pip install pip-audit
          pip-audit --format=json --output=pip-audit-results.json || true

      - name: Upload Security Results
        uses: github/codeql-action/upload-sarif@v3
        if: always() && (matrix.scanner == 'trivy' || matrix.scanner == 'bandit')
        with:
          sarif_file: |
            trivy-results.sarif
            bandit-results.sarif

      - name: Upload Scan Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: python-security-results-${{ matrix.scanner }}
          path: |
            trivy-results.sarif
            snyk-results.json
            bandit-results.json
            bandit-results.sarif
            safety-results.json
            pip-audit-results.json
          retention-days: 30

  generate-report:
    name: Generate Security Report
    runs-on: ubuntu-latest
    needs: security-scan
    if: always()
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download All Results
        uses: actions/download-artifact@v4
        with:
          path: security-results

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install report dependencies
        run: |
          pip install matplotlib plotly pandas jinja2

      - name: Generate Python Security Report
        run: |
          python scripts/generate-security-report.py \
            --project-type python \
            --results-dir security-results \
            --output python-security-dashboard.html \
            --format html \
            --theme dark

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: python-security-dashboard
          path: |
            python-security-dashboard.html
            security-summary.json

  create-security-prs:
    name: Create Python Security PRs
    runs-on: ubuntu-latest
    needs: security-scan
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Security Results
        uses: actions/download-artifact@v4
        with:
          path: security-results

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Apply Python Security Fixes
        run: |
          # Update requirements with secure versions
          if [ -f "requirements-secure.txt" ]; then
            cp requirements-secure.txt requirements.txt
          fi
          
          # Apply bandit fixes
          if [ -f "bandit-fixes.py" ]; then
            python bandit-fixes.py
          fi
          
          # Update Python security configurations
          if [ -f "security_settings.py.template" ]; then
            cp security_settings.py.template security_settings.py
          fi

      - name: Create Security PR
        run: |
          chmod +x scripts/create-security-pr.sh
          ./scripts/create-security-pr.sh \
            --type python \
            --scan-dir security-results \
            --reviewers security-team,python-team
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}